# Generated by Django 3.0 on 2019-12-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobi_number',
            field=models.IntegerField(),
        ),
    ]
